import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const pages = defineCollection({
  loader: glob({
    base: './knowledge/okf',
    pattern: '{fr-CA,en-CA}/**/*.md',
  }),
  schema: z.object({
    type: z.literal('page'),
    id: z.string(),
    title: z.string(),
    description: z.string(),
    slug: z.string(),
    language: z.enum(['fr-CA', 'en-CA']),
    source_of_truth: z.boolean(),
    translation_key: z.string(),
    translation_of: z.string().optional(),
    translation_status: z.enum(['source', 'draft', 'reviewed', 'validated']),
    updated: z.string(),
    nav_label: z.string(),
    nav_order: z.number(),
    hero_eyebrow: z.string(),
    hero_title: z.string(),
    hero_lead: z.string(),
    primary_label: z.string().optional(),
    primary_url: z.string().optional(),
    secondary_label: z.string().optional(),
    secondary_url: z.string().optional(),
    partner_program: z.object({
      model_label: z.string(),
      model_title: z.string(),
      model_description: z.string(),
      availability_note: z.string(),
      support_title: z.string(),
      support_description: z.string(),
      support_items: z.array(z.object({
        title: z.string(),
        description: z.string(),
      })),
      offers_title: z.string(),
      offers_description: z.string(),
      offers: z.array(z.object({
        key: z.enum(['founder', 'gold', 'silver', 'bronze']),
        name: z.string(),
        price: z.string(),
        billing: z.string(),
        availability: z.string(),
        badge: z.string(),
        featured: z.boolean(),
        description: z.string(),
        features: z.array(z.string()),
      })),
      comparison_title: z.string(),
      comparison_description: z.string(),
      comparison_feature_label: z.string(),
      comparison_rows: z.array(z.object({
        feature: z.string(),
        founder: z.string(),
        gold: z.string(),
        silver: z.string(),
        bronze: z.string(),
      })),
      independence_title: z.string(),
      independence_description: z.string(),
      cta_title: z.string(),
      cta_description: z.string(),
      cta_primary_label: z.string(),
      cta_secondary_label: z.string(),
      contact_email: z.string(),
    }).optional(),
  }),
});

export const collections = { pages };
